### ISSUE TITLE
module install seems to be not downloading its actual code?

### ISSUE THREAD

**Issue by NovaLynxie** [treboryx/animalsAPI#3]
Hi there,

I recently updated to v1.2.1 and am now unable to start my application.
Node JS threw this error into the console.
`Error: Cannot find module 'D:/CoraBotReplIt/node_modules/random-animals-api/dist/index.js'. Please verify that the package.json has a valid "main" entry`
Upon further inspection, the package.json "main" currently points towards a non-existent file in the package itself.
Currently it is looking for dist/index.js but the only 'index' file I can see is a src/index.ts in the package files.
Not sure if there was supposed to be a dist/index.js but it seems to be either missing or was replaced with index.ts

**Comment by treboryx** [comment]
Looks about right. `dist` is the build folder, so that's where the index.js file is. You're supposed to build and then run the code.

**Comment by NovaLynxie** [comment]
Huh... interesting. Will give that a try, thought it would have done the build automatically on install but didn't do so.

**Comment by NovaLynxie** [comment]
I tried that, no dice. It now says ./src/index.ts is missing. Inspected the random-animals-api directory in node_modules and it only has the package.json and README.md but no src directory or its index.ts file. Tried reinstalling the module but it seems it does not contain any code files .ts or otherwise.

**Comment by Kvothe838** [comment]
I found this issue too. The error is the following:

`Error: Cannot find module .../node_modules/random-animals-api/dist/index.js'. Please verify that the package.json has a valid "main" entry`

**Comment by bradcornford** [comment]
Same issue here

**Comment by treboryx** [comment]
Hi,

Please update to 1.2.2. Let me know how it goes.

**Comment by Treesnoodle** [comment]
Hey,

I updated to 1.2.2. And i got this error: 
/home/error/Documents/Amie-Source-Code/node_modules/random-animals-api/src/index.ts:1
import superFetch from 'node-superfetch';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/error/Documents/Amie-Source-Code/index.js:9:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by treboryx** [comment]
@OmgImAlexis can you look into this please?

**Comment by OmgImAlexis** [comment]
Main should be pointing to `dist/index.js` not the source. You’ll need to run `build` before publishing to npm. Also add a script called `prepare` with the value of `npm run build` so if anyone uses this directly from GitHub itll auto run the build command.

**Comment by treboryx** [comment]
@OmgImAlexis Thanks!

@everyone else, please try again.

**Comment by NovaLynxie** [comment]
@treboryx I've just tried the latest version v1.2.3, the module is now working as expected and has installed correctly. Thanks again for everyone's help in resolving and fixing the problem.

**Comment by treboryx** [comment]
Thanks for reporting!

**Comment by bradcornford** [comment]
Yeah, can confirm all working here too.
