### ISSUE TITLE
Shiba function is returning undefined

### ISSUE THREAD

**Issue by Arun-kc** [treboryx/animalsAPI#5]
API is throwing `undefined` when trying to use Shiba function

![image](https://user-images.githubusercontent.com/22231409/117570705-06a0c480-b0e9-11eb-85d0-5b48ccc45ff4.png)

Shiba API is returning the value in an array rather than in a JSON object. 

![image](https://user-images.githubusercontent.com/22231409/117570420-a3626280-b0e7-11eb-8262-67869f529a1b.png)

So when you try to get data like `res.body.link`, you will get an `undefined` value since it's not a JSON object.

![image](https://user-images.githubusercontent.com/22231409/117570433-b412d880-b0e7-11eb-98ef-15216c98b94d.png)

So return the URL in the array object instead of `res.body.link`

*PS: Good work with this API, I was planning to build one for my bot, but since I found this I just used this API instead* 👍

**Comment by treboryx** [comment]
Hi. Thanks for reporting this.

Please update to `1.2.6`
