### ISSUE TITLE
how can i update this to npm?

### ISSUE THREAD

**Issue by superintendent2521** [treboryx/animalsAPI#8]
hi owner, uhm i dont exactly know NPM but i do know how to make some modules and i dont exactly know how to update it to the npm module to reflect the newest changes

cheers, outagascar

**Comment by treboryx** [comment]
I'll publish new versions, just let me know

**Comment by superintendent2521** [comment]
Okay, good to know, are u able to publish today or tomorrow?

**Comment by treboryx** [comment]
tomorrow

**Comment by superintendent2521** [comment]
Works for me

**Comment by superintendent2521** [comment]
seems to be that you have forgot. please either give me access to the npm package or publish this, if u would like to give me access to the npm package, please private message me
